---
fan:
  - platform: mqtt
    name: "Ventilation"
    state_topic: "house/attic/wtw/ventilation_level"
    command_topic: "house/attic/wtw/set_ventilation_level"
    speed_state_topic: "house/attic/wtw/ventilation_level"
    speed_command_topic: "house/attic/wtw/set_ventilation_level"
    state_value_template: "{{ states.sensor.wtw_ventilation_level.state }}"
    speed_value_template: "{{ states.sensor.wtw_ventilation_level.state }}"
    payload_off: "1"
    payload_on: "3"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    speeds:
      - "off"
      - low
      - medium
      - high

input_number:
  set_wtw_ventilation_level:
    name: Set ventilation level
    initial: 2
    min: 0
    max: 3
    step: 1
    mode: slider
  set_wtw_comfort_temperature:
    name: Set comfort temperature
    initial: 20
    min: 12
    max: 28
    step: 1
    mode: slider
    unit_of_measurement: '°C'

automation:
  - alias: Ventilation level changed in GUI
    trigger:
      platform: state
      entity_id: input_number.set_wtw_ventilation_level
    action:
      service: mqtt.publish
      data_template:
        topic: house/attic/wtw/set_ventilation_level
        retain: false
        payload: "{{ states('input_number.set_wtw_ventilation_level') | int }}"
  - alias: Comfort temperature changed in GUI
    trigger:
      platform: state
      entity_id: input_number.set_wtw_comfort_temperature
    action:
      service: mqtt.publish
      data_template:
        topic: house/attic/wtw/set_comfort_temperature
        retain: false
        payload: "{{ states('input_number.set_wtw_comfort_temperature') | int }}"

sensor:
  - platform: mqtt
    state_topic: "house/attic/wtw/outside_air_temp"
    name: "WTW Outside Temperature"
    qos: 0
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "house/attic/wtw/supply_air_temp"
    name: "WTW Supply Temperature"
    qos: 0
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "house/attic/wtw/return_air_temp"
    name: "WTW Return Temperature"
    qos: 0
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "house/attic/wtw/exhaust_air_temp"
    name: "WTW Exhaust Temperature"
    qos: 0
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "house/attic/wtw/ventilation_level"
    name: "WTW Ventilation Level"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/filter_status"
    name: "WTW Filter Status"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/intake_fan_speed"
    name: "WTW Intake Fan Speed"
    qos: 0
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "house/attic/wtw/exhaust_fan_speed"
    name: "WTW Exhaust Fan Speed"
    qos: 0
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "house/attic/wtw/comfort_temp"
    name: "WTW Comfort Temperature"
    qos: 0
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: "house/attic/wtw/intake_fan_active"
    name: "WTW Intake Fan Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/intake_fan_speed_rpm"
    name: "WTW Intake Fan RPM"
    qos: 0
    unit_of_measurement: 'rpm'
  - platform: mqtt
    state_topic: "house/attic/wtw/exhaust_fan_speed_rpm"
    name: "WTW Exhaust Fan RPM"
    qos: 0
    unit_of_measurement: 'rpm'
  - platform: mqtt
    state_topic: "house/attic/wtw/bypass_factor"
    name: "WTW Bypass Factor"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/bypass_step"
    name: "WTW Bypass Step"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/bypass_correction"
    name: "WTW Bypass Correction"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/summer_mode"
    name: "WTW Summer Mode"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/valve_bypass_percentage"
    name: "WTW Bypass Valve"
    qos: 0
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "house/attic/wtw/bypass_motor_current"
    name: "WTW Motor Current Bypass"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/preheating_motor_current"
    name: "WTW Motor Current Preheating"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/preheating_present"
    name: "WTW Preheating Present"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/bypass_present"
    name: "WTW Bypass Present"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/type"
    name: "WTW Type"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/size"
    name: "WTW Size"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/options_present"
    name: "WTW Options Present"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/activestatus1"
    name: "WTW Active Status 1"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/activestatus2"
    name: "WTW Active Status 2"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/activestatus3"
    name: "WTW Active Status 3"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/enthalpy_present"
    name: "WTW Enthalpy Present"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/ewt_present"
    name: "WTW EWT Present"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/level0_hours"
    name: "WTW Level 0 Hours"
    qos: 0
    unit_of_measurement: 'hr'
  - platform: mqtt
    state_topic: "house/attic/wtw/level1_hours"
    name: "WTW Level 1 Hours"
    qos: 0
    unit_of_measurement: 'hr'
  - platform: mqtt
    state_topic: "house/attic/wtw/level2_hours"
    name: "WTW Level 2 Hours"
    qos: 0
    unit_of_measurement: 'hr'
  - platform: mqtt
    state_topic: "house/attic/wtw/level3_hours"
    name: "WTW Level 3 Hours"
    qos: 0
    unit_of_measurement: 'hr'
  - platform: mqtt
    state_topic: "house/attic/wtw/frost_protection_hours"
    name: "WTW Frost Protection Hours"
    qos: 0
    unit_of_measurement: 'hr'
  - platform: mqtt
    state_topic: "house/attic/wtw/preheating_hours"
    name: "WTW Preheating Hours"
    qos: 0
    unit_of_measurement: 'hr'
  - platform: mqtt
    state_topic: "house/attic/wtw/bypass_open_hours"
    name: "WTW Bypass Open Hours"
    qos: 0
    unit_of_measurement: 'hr'
  - platform: mqtt
    state_topic: "house/attic/wtw/filter_hours"
    name: "WTW Filter Hours"
    qos: 0
    unit_of_measurement: 'hr'
  - platform: mqtt
    state_topic: "house/attic/wtw/preheating_valve"
    name: "WTW Preheating Valve"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/preheating_valve"
    name: "WTW Valve Preheating"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/frost_protection_active"
    name: "WTW Frost Protection Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/preheating_state"
    name: "WTW Preheating State"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/frost_protection_minutes"
    name: "WTW Frost Protection Minutes"
    qos: 0
    unit_of_measurement: 'min'
  - platform: mqtt
    state_topic: "house/attic/wtw/frost_protection_level"
    name: "WTW Frost Protection Level"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/return_air_level"
    name: "WTW Return Air Level"
    qos: 0
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: "house/attic/wtw/supply_air_level"
    name: "WTW Supply Air Level"
    qos: 0
    unit_of_measurement: '%'

  - platform: mqtt
    state_topic: "house/attic/wtw/P10_active"
    name: "WTW P10 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P11_active"
    name: "WTW P11 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P12_active"
    name: "WTW P12 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P13_active"
    name: "WTW P13 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P14_active"
    name: "WTW P14 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P15_active"
    name: "WTW P15 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P16_active"
    name: "WTW P16 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P17_active"
    name: "WTW P17 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P18_active"
    name: "WTW P18 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P19_active"
    name: "WTW P19 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P90_active"
    name: "WTW P90 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P91_active"
    name: "WTW P91 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P92_active"
    name: "WTW P92 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P93_active"
    name: "WTW P93 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P94_active"
    name: "WTW P94 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P95_active"
    name: "WTW P95 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P96_active"
    name: "WTW P96 Active"
    qos: 0
  - platform: mqtt
    state_topic: "house/attic/wtw/P97_active"
    name: "WTW P97 Active"
    qos: 0
